---
- include: ssh-sync.yml
- include: cm-server.yml
- include: cm-agent.yml server={{ groups['cm-server'][0] }}
- hosts: all
  remote_user: centos
  tasks:
    - name: restart machine
      command: reboot
      poll: 5
      async: 30
      become: yes
      ignore_errors: True
      tags: reboot
    - name: wait for server come back
      local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=300
      tags: reboot
